### PR TITLE
2667204 Pass context into displayCurrentSelection()

### PR DESCRIPTION
**Pull request by jfrederick**
https://www.drupal.org/node/2667204

Just pass some context into the field widget's helper function. Makes it easier to extend this widget and add custom functionality.

### CODE REVIEW

**Comment by Berdir** [comment]
Note that this will break the subclass in file_entity. Not saying that we shouldn't do it, just that that will have to be updated as well then.

As an alternative, what I did there as well for something, is to override the form method and store what you need in $this->.something.

**Comment by jfrederick** [comment]
Oh thanks @Berdir, that's a simple way to do it. Given that, I could live without this feature. Either way!

**Comment by slashrsm** [comment]
I have run into situations where context would help a lot in the past. Specially form_state. We didn't end up adding that since we wanted to support using entity browser outside of forms as well. 

However, the more I think about this the more it seems we might want to do that since it would make our life much easier. Using EB outside of forms is probably something that is very unlikely to happen anyway. 

May I ask you what is your situation that required this?

**Comment by jfrederick** [comment]
@slashrsm in my case, i am using a slightly enhanced entity reference field. it has data properties in addition to target_id. These data properties give context to the reference without having something as full-blown as Relation module in between. And I want to expose those fields for editing alongside each of the rendered entities.

Put another way, displayCurrentSelection() shows the entity reference relationships, which are usually entirely described by a target_id, which then gets rendered. I need to display additional field form elements along with the rendered entities.

My case is pretty custom. But if someone were using Relation module (or the workaround where you use EntityReference to a middle connecting object), they may similarly want to expose some of the fields on the Relation object, so that those fields can be edited inline?

**Comment by slashrsm** [comment]
@jfrederick you should check field widgets that @Berdir created in file_entity. They are based on the default entity reference widget too and designed to work with file and image fields (which also have additional properties). You won't be able to replace your custom widget with them, but maybe you can re-use some code/ideas.

**Comment by slashrsm** [comment]
Another thing.... #118 aims to create the entity browser form element, which will have access to much more context than displayEntityBrowser(). I think having a form element is the way to go forward. Could you check that PR and evaluate if it would solve your needs too?

**Comment by primsi** [comment]
I paused working on #118 a bit, because there were some open questions we needed to discuss. The biggest was what should said element do: just provide a way to access the eb widget or also display current selection. The more stuff we add the more complicated the element becomes to use.

**Pull request closed without merging**
